[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ExcelReaders = "c04bee98-12a5-510c-87df-2a230cb6e075"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
